#!/usr/bin/env python3
"""
The card-drift gate  (AMB.2, 2026-07-25)

WHY THIS EXISTS
    A design system was already built for this app once. cardStyle() shipped
    during the audit roadmap's Phase 3 and NOTHING EVER CALLED IT, while 115
    hand-rolled card backgrounds went on being written across 39 files. The
    lesson was not "write a design system" — that was done, and it failed. A
    design system with no enforcement is decoration.

    So this gate fails a write that hand-rolls a card. Existing cards are
    grandfathered per file WITH THEIR CURRENT COUNT, so a grandfathered file can
    shrink but never grow: converting is allowed, adding card number eight to
    DashboardWidgets is not. Each AMB phase deletes its entry as it converts.

WHAT COUNTS AS A HAND-ROLLED CARD
    Two shapes, both real in this codebase:

      SHADOWED      a rounding and a .shadow( close together —
                    .cornerRadius(12) + .shadow(...), or
                    RoundedRectangle(...).fill(...).shadow(...)

      ROUNDED FILL  a rounding used as a BACKGROUND, shadow or not —
                    .background(.ultraThinMaterial, in: RoundedRectangle(...))
                    .background(RoundedRectangle(...).fill(...))

    The second rule was added after an audit showed the shadow rule alone had
    roughly half the recall it claimed: EIGHT of the ten cards AMB.2 itself
    converted carry no shadow, and the Ambient idiom IS a shadowless material
    fill. A gate blind to the app's dominant card shape is worse than no gate,
    because it reports green.

    A rounding that is only an edge (.strokeBorder / .stroke) or a mask
    (.clipShape) is not a container and never counts. .ambientCard(...) trips
    nothing, because it contains neither token at the call site — the sanctioned
    path is invisible to the gate and every other path is not.

HOW IT RUNS
    hook     (default) PreToolUse on Write|Edit. Reads the payload on stdin,
             reconstructs what the file WOULD contain after the edit, and exits
             2 to block. FAILS OPEN on every error — a broken gate must never
             stop work.
    --sweep  scan the app; exit 1 if any file exceeds its allowance. Run this
             before declaring a phase done; it is also the only thing that
             catches a card written by a shell command, which the hook cannot
             see (it only matches Write and Edit).
    --list   print every card including grandfathered ones, and emit a ready-to
             -paste ALLOWLIST. The allowlist is GENERATED from the rule rather
             than hand-written, so the green start is a fact, not a hope.

    Modelled on ~/.claude/hooks/protect-captura-files.sh (Python too, despite
    the extension) — same contract: JSON on stdin, fail open, exit 2 plus an
    explanatory sentence on stderr.
"""

import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_DIR = os.path.join(REPO, "Iconik Employee")

# Directories allowed to build containers.
#   DesignSystem  is where the one card lives.
#   DesignLab     is the mockup harness (D10). Its whole job is to prototype
#                 treatments the primitive cannot yet express so the operator
#                 can choose one — gating it would defeat the hard gate it
#                 serves. A treatment that survives review gets promoted INTO
#                 AmbientCard before the real screens are converted.
EXEMPT_DIRS = ("DesignSystem", "DesignLab")

# How far apart two tokens can sit and still be one card, counted in CODE lines
# — comment lines are removed before measuring. They used to count, which meant
# a long comment explaining a card pushed its own tokens out of range and
# silently hid it. That had already happened once, inside this repo, on the
# first day.
PROXIMITY = 5

ROUNDING = re.compile(r"RoundedRectangle\s*\(|\.cornerRadius\s*\(")
SHADOW = re.compile(r"\.shadow\s*\(")
BACKGROUND = re.compile(r"\.background\s*\(")
FILL = re.compile(r"\.fill\s*\(")
EDGE_ONLY = re.compile(r"\.strokeBorder\s*\(|\.stroke\s*\(|\.clipShape\s*\(")
COMMENT = re.compile(r"^\s*(//|\*|/\*)")

# Per-SITE opt-out for things that are rounded and filled but are not cards: a
# selection chip, a photo hero, a keyboard key, a drop shadow on a glyph.
# Must be a COMMENT and must carry a reason, so it cannot be tripped by a string
# literal and cannot be dropped in without saying why.
ALLOW_MARKER = re.compile(r"^\s*(?://|\*|/\*)\s*ambient-allow:\s*\S+")

# ---------------------------------------------------------------------------
# Grandfathered: path -> (owning phase, number of cards allowed to remain).
#
# Generated by --list on 2026-07-25. The COUNT is the load-bearing part: a file
# here may shrink but never grow, so conversion is unobstructed while a new card
# in DashboardWidgets — the highest-drift file in the app — is still refused.
# Delete the entry entirely when its phase converts the file.
# ---------------------------------------------------------------------------
ALLOWLIST = {}  # populated below by _load_allowlist()

_ALLOWLIST_SOURCE = """
Iconik Employee/AllFeaturesView.swift|AMB.12|1
Iconik Employee/Chat/Views/MessageInputAccessoryView.swift|AMB.6|1
Iconik Employee/Components/AddressAutocompleteField.swift|AMB.12|2
Iconik Employee/Components/LoadingOverlay.swift|AMB.12|1
Iconik Employee/DashboardWidgets.swift|AMB.4|8
Iconik Employee/Equipment Feature/Views/Components/EquipmentCard.swift|AMB.3|1
Iconik Employee/Equipment Feature/Views/Components/KitCard.swift|AMB.3|2
Iconik Employee/MainEmployeeView.swift|AMB.4|2
Iconik Employee/Misc Features/CustomDailyReportsView.swift|AMB.7|2
Iconik Employee/Misc Features/DailyJobReportView.swift|AMB.7|2
Iconik Employee/Misc Features/LocationPhotoAttachmentView.swift|AMB.7|6
Iconik Employee/Misc Features/MileageReportsView.swift|AMB.7|2
Iconik Employee/Misc Features/RoutePlannerView.swift|AMB.7|1
Iconik Employee/Misc Features/TemplateFormView.swift|AMB.7|2
Iconik Employee/Misc Features/TemplateReportListView.swift|AMB.7|2
Iconik Employee/NFC/DeleteConfirmationAlert.swift|AMB.11|1
Iconik Employee/NFC/JobBoxNotification.swift|AMB.11|2
Iconik Employee/NFC/ScanView.swift|AMB.11|2
Iconik Employee/NFC/StatisticsView.swift|AMB.11|6
Iconik Employee/Schedule/RealTimeSyncIndicator.swift|AMB.1 residual|1
Iconik Employee/SessionSelectionView.swift|AMB.12|1
Iconik Employee/Settings/EmployeeInfoView.swift|AMB.12|1
Iconik Employee/Settings/SchoolDetailView.swift|AMB.12|3
Iconik Employee/StatsView.swift|AMB.9|7
Iconik Employee/TimeEntryListView.swift|AMB.12|2
Iconik Employee/TimeOff/Views/MyTimeOffRequestsView.swift|AMB.8|1
Iconik Employee/TimeOff/Views/TimeOffApprovalView.swift|AMB.8|1
Iconik Employee/TimeTrackingButton.swift|AMB.12|2
Iconik Employee/TimeTrackingMainView.swift|AMB.12|2
Iconik Employee/Training/Components/CritiqueGridCard.swift|AMB.12|1
Iconik Employee/Training/Components/CritiqueListCard.swift|AMB.12|1
Iconik Employee/Training/Components/StatsCard.swift|AMB.12|1
Iconik Employee/UIComponents.swift|AMB.12|1
Iconik Employee/Sports Shoot Feature/CaptureGalleryListView.swift|out of scope (D1)|1
Iconik Employee/Sports Shoot Feature/CapturaSportsRosterView_iPhone.swift|out of scope (D1)|2
Iconik Employee/Sports Shoot Feature/CapturaSportsView.swift|out of scope (D1)|2
Iconik Employee/Sports Shoot Feature/CustomKeyboardTextField.swift|out of scope (D1)|2
Iconik Employee/Sports Shoot Feature/CustomNumberKeyboard.swift|out of scope (D1)|5
Iconik Employee/Sports Shoot Feature/FPSportsMultiPhotoImporter.swift|out of scope (D1)|1
Iconik Employee/Sports Shoot Feature/FPSportsRosterView_iPad.swift|out of scope (D1)|4
Iconik Employee/Sports Shoot Feature/FloatingNumberKeypad.swift|out of scope (D1)|4
Iconik Employee/Sports Shoot Feature/KeyboardManager.swift|out of scope (D1)|2
Iconik Employee/Sports Shoot Feature/MultiPhotoRosterImporterView.swift|out of scope (D1)|1
Iconik Employee/Sports Shoot Feature/PoserStationView.swift|out of scope (D1)|4
Iconik Employee/Sports Shoot Feature/RegistrationKioskView.swift|out of scope (D1)|1
Iconik Employee/Sports Shoot Feature/SyncStatusBadge.swift|out of scope (D1)|1
"""


def _load_allowlist():
    for line in _ALLOWLIST_SOURCE.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        path, phase, count = line.rsplit("|", 2)
        ALLOWLIST[path] = (phase, int(count))


_load_allowlist()


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

def repo_relative(path):
    try:
        return os.path.relpath(os.path.realpath(path), REPO).replace(os.sep, "/")
    except ValueError:
        return path


def parts_of(rel_path):
    return [p for p in rel_path.split("/") if p]


def inside_app(rel_path):
    """True only for the app target — compared component-wise, so the sibling
    'Iconik EmployeeTests' target is NOT swept up by a string prefix."""
    parts = parts_of(rel_path)
    return len(parts) > 1 and parts[0] == "Iconik Employee"


def in_exempt_dir(rel_path):
    """Component-wise, so a directory named DesignSystemScratch is not exempt."""
    return any(part in EXEMPT_DIRS for part in parts_of(rel_path))


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

def find_cards(text):
    """Return [(line_number, line_text)] for every hand-rolled card container."""
    raw = text.splitlines()

    # Measure distance in CODE lines only. `keep` maps a compacted index back to
    # the real line number so reports still point at the right place.
    code, keep = [], []
    for index, line in enumerate(raw):
        if COMMENT.match(line) or not line.strip():
            continue
        code.append(line)
        keep.append(index)

    # A marker suppresses the nearest following card. Recorded against the next
    # code line so it travels with the construct it explains.
    suppressed_code_lines = set()
    for index, line in enumerate(raw):
        if not ALLOW_MARKER.match(line):
            continue
        for position, original in enumerate(keep):
            if original > index:
                for offset in range(0, PROXIMITY + 1):
                    if position + offset < len(code):
                        suppressed_code_lines.add(position + offset)
                break

    hits = []
    seen = set()

    def window(position, span):
        return max(0, position - span), min(len(code), position + span + 1)

    for position, line in enumerate(code):
        if position in suppressed_code_lines:
            continue

        low, high = window(position, PROXIMITY)

        if SHADOW.search(line) and any(ROUNDING.search(code[j]) for j in range(low, high)):
            number = keep[position] + 1
            if number not in seen:
                seen.add(number)
                hits.append((number, line.strip()))
            continue

        if not ROUNDING.search(line) or EDGE_ONLY.search(line):
            continue

        near_low, near_high = window(position, 2)
        as_background = any(BACKGROUND.search(code[j]) for j in range(near_low, position + 1))
        if not as_background:
            continue
        filled = any(FILL.search(code[j]) for j in range(position, near_high))
        shaped = any("in:" in code[j] for j in range(position, near_high))
        if not (filled or shaped):
            continue

        number = keep[position] + 1
        if number not in seen:
            seen.add(number)
            hits.append((number, line.strip()))

    return hits


# ---------------------------------------------------------------------------
# Hook
# ---------------------------------------------------------------------------

def resulting_content(payload):
    """What the file will contain once this tool call lands."""
    tool = payload.get("tool_name", "")
    tool_input = payload.get("tool_input") or {}
    if not isinstance(tool_input, dict):
        return None, None
    path = tool_input.get("file_path") or ""
    if not isinstance(path, str) or not path:
        return None, None

    if tool == "Write":
        content = tool_input.get("content")
        return path, content if isinstance(content, str) else ""

    if tool == "Edit":
        old = tool_input.get("old_string")
        new = tool_input.get("new_string")
        old = old if isinstance(old, str) else ""
        new = new if isinstance(new, str) else ""
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                current = handle.read()
        except OSError:
            return path, new
        if tool_input.get("replace_all"):
            return path, current.replace(old, new)
        return path, current.replace(old, new, 1)

    return None, None


def run_hook():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0
    if not isinstance(payload, dict):
        return 0
    if payload.get("tool_name") not in ("Write", "Edit"):
        return 0

    path, content = resulting_content(payload)
    if not path or not path.lower().endswith(".swift"):
        return 0

    rel = repo_relative(path)
    if not inside_app(rel) or in_exempt_dir(rel):
        return 0

    hits = find_cards(content or "")
    if not hits:
        return 0

    # The test is "does this edit make it WORSE", not "is this file clean".
    #
    # Comparing against the file on disk is what lets a conversion proceed one
    # card at a time: turning card 1 of 7 into .ambientCard leaves six behind,
    # and a clean-file test would refuse that edit — locking the gate against
    # the very work it exists to encourage. It also means a file can never gain
    # a card, which is the property that actually matters. The allowlist counts
    # are the ratchet for --sweep; this is the ratchet for each edit.
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            before = len(find_cards(handle.read()))
    except OSError:
        before = 0  # new file

    if len(hits) <= before:
        return 0

    phase, allowance = ALLOWLIST.get(rel, (None, 0))
    added = hits[before:]
    where = "\n".join(f"    line {number}: {text}" for number, text in added[:6])
    if phase:
        headline = (
            f"BLOCKED by check-card-drift: {rel} is grandfathered at {allowance} "
            f"hand-rolled card(s) for {phase}. This edit takes it from {before} "
            f"to {len(hits)}. A grandfathered file may shrink, never grow."
        )
    else:
        headline = (
            f"BLOCKED by check-card-drift: this edit adds a hand-rolled card to "
            f"{rel} ({before} before, {len(hits)} after)."
        )

    print(
        f"{headline}\n{where}\n\n"
        "A rounded, filled container is a CARD, and this app has exactly one: "
        ".ambientCard(density:state:border:glow:fillWidth:contentAlignment:) in "
        "DesignSystem/AmbientCard.swift. Densities are .hero / .roomy / .compact.\n\n"
        "If it genuinely is NOT a card — a button, a keyboard key, a selection "
        "chip, a drop shadow on an image — put a reasoned marker on the line "
        "above it:\n"
        "    // ambient-allow: this is the FAB, not a card\n\n"
        "If the primitive cannot express what you need, EXTEND AmbientCard.swift. "
        "Do not hand-roll one here, and do not widen the allowlist in "
        "scripts/check_card_drift.py without asking the operator first — that "
        "blinds the gate to the whole file, which is how the previous card "
        "modifier ended up with zero adopters.",
        file=sys.stderr,
    )
    return 2


# ---------------------------------------------------------------------------
# Sweep
# ---------------------------------------------------------------------------

def walk_swift():
    for root, dirs, files in os.walk(APP_DIR):
        dirs[:] = [d for d in dirs if d not in EXEMPT_DIRS]
        for name in files:
            if name.lower().endswith(".swift"):
                yield os.path.join(root, name)


def scan_all():
    found = {}
    for path in sorted(walk_swift()):
        rel = repo_relative(path)
        if in_exempt_dir(rel):
            continue
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                hits = find_cards(handle.read())
        except OSError as exc:
            print(f"  ! could not read {rel}: {exc}", file=sys.stderr)
            continue
        if hits:
            found[rel] = hits
    return found


def run_scan(emit_allowlist):
    found = scan_all()
    over, dead = [], []

    for rel, hits in sorted(found.items()):
        phase, allowance = ALLOWLIST.get(rel, (None, 0))
        if len(hits) > allowance:
            over.append((rel, hits, phase, allowance))

    for rel, (phase, allowance) in ALLOWLIST.items():
        actual = len(found.get(rel, []))
        if actual < allowance:
            dead.append((rel, phase, allowance, actual))

    if emit_allowlist:
        total = sum(len(v) for v in found.values())
        print(f"{len(found)} files, {total} hand-rolled cards.\n")
        print("Paste into _ALLOWLIST_SOURCE:\n")
        for rel, hits in sorted(found.items()):
            phase = ALLOWLIST.get(rel, ("UNASSIGNED", 0))[0]
            print(f"{rel}|{phase}|{len(hits)}")
        print()

    status = 0
    if over:
        print(f"CARD DRIFT — {len(over)} file(s) over their allowance:")
        for rel, hits, phase, allowance in over:
            label = f"grandfathered {allowance} for {phase}" if phase else "not grandfathered"
            print(f"  {rel}  ({len(hits)} found, {label})")
            for number, text in hits[allowance:]:
                print(f"      line {number}: {text}")
        status = 1
    else:
        print("Card drift: clean. No file exceeds its allowance.")

    # Reported even when the sweep is red: a shrunk allowance is a phase that
    # did work and forgot to tighten the gate behind it.
    if dead:
        print(f"\n{len(dead)} allowance(s) now too generous — tighten or delete:")
        for rel, phase, allowance, actual in dead:
            print(f"  {rel}  [{phase}]  allows {allowance}, found {actual}")

    return status


def main():
    if "--sweep" in sys.argv:
        return run_scan(emit_allowlist=False)
    if "--list" in sys.argv:
        return run_scan(emit_allowlist=True)
    return run_hook()


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # never wedge the session
        print(f"[check-card-drift] failing open: {exc}", file=sys.stderr)
        sys.exit(0)
